import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Layout from "@/components/layout/Layout";
import {Inter} from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],       // You can specify subsets like 'latin' or 'latin-ext'
  weight: ['100', '400', '600', '900'], // Specify the weights you need
  variable: '--font-inter', // Optional: Use a CSS variable to apply it globally
});

export const metadata: Metadata = {
  title: "Thereviewindex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/tu-berlin-logo-long-red.svg" type="image/x-icon" />
      </head>
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Layout>
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
